---
# Install LAP stack (No MySQL)

- name: Install apache2, php5
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - php5
   - libapache2-mod-php5
  become: yes
  become_user: root

- name: Enable FW access to Apache2
  ufw: rule=allow port={{ item }}
  with_items:
   - 80
   - 443
  become: yes
  become_user: root
